# Generated by Django 5.1.2 on 2024-11-12 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ja', models.CharField(max_length=100, verbose_name='アメニティ名（日本語）')),
                ('name_en', models.CharField(max_length=100, verbose_name='Amenity Name (English)')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ja', models.CharField(max_length=255, verbose_name='質問（日本語）')),
                ('answer_ja', models.TextField(verbose_name='回答（日本語）')),
                ('question_en', models.CharField(max_length=255, verbose_name='Question (English)')),
                ('answer_en', models.TextField(verbose_name='Answer (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ja', models.CharField(max_length=100, verbose_name='設備名（日本語）')),
                ('name_en', models.CharField(max_length=100, verbose_name='Feature Name (English)')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='施設ID')),
                ('roomid', models.CharField(max_length=50, unique=True, verbose_name='部屋ID')),
                ('name_ja', models.CharField(max_length=100, verbose_name='施設名（日本語）')),
                ('name_en', models.CharField(max_length=100, verbose_name='Facility Name (English)')),
                ('location_ja', models.CharField(max_length=255, verbose_name='所在地（日本語）')),
                ('location_en', models.CharField(max_length=255, verbose_name='Location (English)')),
                ('map_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Maps Link')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='定員')),
                ('description_ja', models.TextField(blank=True, verbose_name='説明文（日本語）')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catchphrase_ja', models.CharField(blank=True, max_length=255, verbose_name='キャッチコピー（日本語）')),
                ('catchphrase_en', models.CharField(blank=True, max_length=255, verbose_name='Catchphrase (English)')),
                ('amenities', models.ManyToManyField(blank=True, related_name='facilities', to='facilities.amenity')),
                ('features', models.ManyToManyField(blank=True, related_name='facilities', to='facilities.feature')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility_images/')),
                ('alt_text_ja', models.CharField(blank=True, max_length=255, verbose_name='代替テキスト（日本語）')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, verbose_name='Alt Text (English)')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.facility')),
            ],
        ),
    ]
