# Generated by Django 5.1.2 on 2024-11-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_reservation_check_in_date_reservation_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
    ]
