# Generated by Django 5.1.2 on 2024-11-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_reservation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='base_guests',
            field=models.PositiveIntegerField(default=2, verbose_name='ベース人数'),
        ),
        migrations.AddField(
            model_name='facility',
            name='base_price',
            field=models.PositiveIntegerField(default=10000, verbose_name='ベース料金 (JPY)'),
        ),
        migrations.AddField(
            model_name='facility',
            name='extra_guest_price',
            field=models.PositiveIntegerField(default=2000, verbose_name='追加ゲスト1人あたりの料金 (JPY)'),
        ),
    ]
