# Generated by Django 5.1.2 on 2024-11-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_facility_base_guests_facility_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='prop_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='プロパティキー'),
        ),
    ]
