# Generated by Django 5.1.2 on 2025-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_facility_prop_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='description_ja',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='name_ja',
        ),
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='address_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='address_zh',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='amenities_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='amenities_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='amenities_text_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='facility',
            name='description_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='location_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='facility',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='name_zh',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=0, verbose_name='駐車可能台数'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
