# Generated by Django 6.0.3 on 2026-04-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_remove_facility_description_ja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='booking_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Booking.com Link'),
        ),
    ]
