# Generated by Django 5.1.2 on 2024-12-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('address1', models.CharField(max_length=255, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='Address 2')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='未設定', max_length=100, unique=True, verbose_name='Name (English)')),
                ('name_ja', models.CharField(default='未設定', max_length=100, unique=True, verbose_name='Name (Japanese)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='未設定', max_length=255, verbose_name='Product Name (English)')),
                ('name_ja', models.CharField(default='未設定', max_length=255, verbose_name='Product Name (Japanese)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Description (English)')),
                ('description_ja', models.TextField(blank=True, default='', verbose_name='Description (Japanese)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('genres', models.ManyToManyField(related_name='products', to='shop.genre', verbose_name='Genres')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Product')),
            ],
        ),
    ]
