# Generated by Django 5.1.2 on 2024-12-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerinfo',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='buyerinfo',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='buyerinfo',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AddField(
            model_name='buyerinfo',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='buyerinfo',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Shipping Cost'),
        ),
        migrations.AddField(
            model_name='buyerinfo',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price'),
        ),
    ]
