server {
    listen 80;
    server_name hakodate-tomoe.com www.hakodate-tomoe.com;

    # Certbot verification
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name hakodate-tomoe.com www.hakodate-tomoe.com;

    # SSL certificates (Certbot)
    ssl_certificate /etc/letsencrypt/live/hakodate-tomoe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hakodate-tomoe.com/privkey.pem;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;

    # Frontend (React App & its static files)
    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # All static files - Default to Frontend (React)
    location /static/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend API & Admin
    location ~ ^/(api|admin) {
        proxy_pass http://127.0.0.1:8100;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Media Files
    location /media/ {
        root /var/www/tomoe_web;
        charset utf-8;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Django Admin / Rest Framework Static Files
    location /static/admin/ {
        alias /var/www/tomoe_web/staticfiles/admin/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /static/rest_framework/ {
        alias /var/www/tomoe_web/staticfiles/rest_framework/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
