"""
Django settings for guesthouse_tomoe project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-0k)v*tr-g-mn9q&4z3_vdh-d*yu9p%2#4cjleur4#2z^w-ir)w')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost 127.0.0.1').split(' ')


DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'facilities',
    'rest_framework',
    'corsheaders',
    'shop',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
]

ROOT_URLCONF = 'guesthouse_tomoe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # テンプレートフォルダのパス

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'guesthouse_tomoe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=False)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'  # 静的ファイルのURL

# collectstaticで収集された静的ファイルの保存先
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Reactのビルドディレクトリやその他の静的ファイルディレクトリ
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'templates'),  # Reactのビルドディレクトリなど
    os.path.join(BASE_DIR, 'static'),  # 必要に応じて追加
]



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'


# REST_FRAMEWORK = {
#     'DEFAULT_RENDERER_CLASSES': [
#         'rest_framework.renderers.JSONRenderer',
#     ] if not os.environ.get('DEBUG') else [
#         'rest_framework.renderers.JSONRenderer',
#         'rest_framework.renderers.BrowsableAPIRenderer',  # ブラウザでの表示を有効にする
#     ],
# }
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # JSONのみ有効
    ],
}

# INSTALLED_APPS += ['corsheaders']

MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')

#CORS_ALLOW_ALL_ORIGINS = True  # 開発時は全てのオリジンを許可

CORS_ALLOWED_ORIGINS = [
    'https://www.hakodate-tomoe.com',  # Reactアプリのオリジン
    'https://hakodate-tomoe.com',  # 必要に応じて追加
]


MEDIA_URL = '/media/'  # URLパス
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 実際の保存先
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media/')



BEDS24_API_KEY = '8qdoj3MLS6KJqjBTAZW8PDXGtw8rp1wg'
BEDS24_PROP_KEY = 'あなたのプロパティキー'



# テスト環境
# STRIPE_SECRET_KEY = 'sk_test_51EdXAnKrki57bLDpvkWjk0fOv91o3T2NxYPl85jF4IGNYo6IL0v08Xk83Dvcdsz2QNCVZWtUpiBTnjuA91rMGPyV003ln3Y8xu'
# ENDPOINT_SECRET = 'whsec_tlgrpdcHCAIilpdcvsPIJwbaSFvgsFZq'
# SHOP_ENDPOINT_SECRET = 'whsec_dTkehWoUSeNt3ugD1k5JVJVE56RsumPf'
# ENDPOINT_SECRET = 'we_1QWvUhKrki57bLDpOI2jpVrn'

# 本番環境
STRIPE_SECRET_KEY = 'sk_live_7JngbNAxHq81tKGFsD1aqZ5h004ZF1UArY'
ENDPOINT_SECRET = 'whsec_07z0lFYnXmKBP3Plsfdoy07TuIzWtrX5'
SHOP_ENDPOINT_SECRET = 'whsec_pj8TMizavj5CcXmNSbYpP6LCBJqlEzcl'


EMAILPASSWORD = "ucoxgewctksnnokl"
EMAILPORT = 587



# 1) メールバックエンド (SMTP) を使用
# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2) SMTP サーバ情報
EMAIL_HOST = 'localhost'     # VPS 上の Postfix を使う場合は 'localhost'
EMAIL_PORT = 25              # Submission ポート(587) を使う場合は 587
EMAIL_HOST_USER = ''         # 基本的にローカルSMTPなら未設定
EMAIL_HOST_PASSWORD = ''     # 同上
EMAIL_USE_TLS = False        # 必要に応じて True
EMAIL_USE_SSL = False        # 必要に応じて True

# 3) 送信元の既定アドレス(From) を設定 (任意)
DEFAULT_FROM_EMAIL = 'no-reply@hakodate-tomoe.com'




# Gmailを使う場合
# EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTPサーバー
# EMAIL_PORT = 587  # GmailのSMTPポート
# EMAIL_USE_TLS = True  # TLSを使用
# EMAIL_HOST_USER = 'hakodateshino0901@gmail.com'  # Gmailアドレス
# EMAIL_HOST_PASSWORD = 'yrvm qgfx ywgu owms'  # Gmailアプリパスワード
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 送信元メールアドレス

# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
BCC = [
    'hakodate2pack@yahoo.co.jp',
    'wisteria07930791@gmail.com',
    'hakodateshino0901@gmail.com',
]



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/error.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}


# settings.py
CSRF_TRUSTED_ORIGINS = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost:3000').split(' ')

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    X_FRAME_OPTIONS = 'DENY'



